name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - name: Install
        run: pipenv install --dev

      - name: Lint
        run: pipenv run pylint **/*.py

      - name: Test
        run: pipenv run pytest
